Parameters:
  Int:
    Type: Number
    Default: 500000000

  Float:
    Type: Number
    Default: 12345.6789

  AccountID:
    Type: String
    Default: 0123456789

Resources:
  Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Base64:
          Ref: Cakes

  Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Base64
        Ref: Cakes # Nested ref comment
      Tags:
        - Key: Empty
          Value: !Sub ""

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /

Outputs:
  Bucket1Arn:
    Value: !GetAtt Bucket1.Arn # Short GetAtt comment
  Bucket1Name:
    Value: !Ref Bucket1 # Ref comment
  Bucket2Arn:
    Value:
      Fn::GetAtt: # GetAtt comment
        - Bucket2 # Bucket2 comment
        - Arn # Arn comment
AWSTemplateFormatVersion: 2010-09-09
